# Generated by Django 4.2.9 on 2025-02-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='KMVnwI6xDkLfcZ9a1tpqENKVMbChk2H2', editable=False, max_length=32, unique=True),
        ),
    ]
