# Generated by Django 4.2.9 on 2025-02-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='42GiMOElScoIpfNK84TnHZ5AHXgrY970', editable=False, max_length=32, unique=True),
        ),
    ]
